"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Row = Record<string, string | number | null>;
type Data = {vehicles:Row[]; people:Row[]; routes:Row[]; schedules:Row[]; mileageFuelLogs:Row[]; maintenanceLogs:Row[]; driverActivity:Row[]; driverAttendance:Row[]};
const empty:Data={vehicles:[],people:[],routes:[],schedules:[],mileageFuelLogs:[],maintenanceLogs:[],driverActivity:[],driverAttendance:[]};

const Icon=({children}:{children:string})=><span className="icon">{children}</span>;

export default function FleetPortal({userName}:{userName:string}) {
  const [data,setData]=useState<Data>(empty); const [tab,setTab]=useState("Overview");
  const [modal,setModal]=useState(""); const [view,setView]=useState<"manager"|"viewer">("manager");
  const [loading,setLoading]=useState(true); const [toast,setToast]=useState("");
  const load=()=>fetch("/api/fleet").then(r=>r.json()).then(d=>{setData(d);setLoading(false)});
  useEffect(()=>{load()},[]);
  const today=new Date().toLocaleDateString("en-SG",{weekday:"long",day:"numeric",month:"long"});
  const drivers=data.people.filter(p=>p.role==="Driver"), assistants=data.people.filter(p=>p.role==="Assistant");
  const available=data.vehicles.filter(v=>v.status==="Available").length;
  const nav=[['Overview','⌂'],['Vehicles','▣'],['Mileage & Fuel','◉'],['Maintenance','⚙'],['Driver Activity','●'],['Drivers & Assistants','♙'],['Routes','⌁'],['Schedule','□']];
  const title=tab==="Overview"?"Good morning, dispatcher.":tab;
  const subtitle=tab==="Overview"?`${today} · Here’s what’s moving today.`:`Manage and review your ${tab.toLowerCase()} records.`;
  function saved(){setModal("");setToast("Record saved successfully");load();setTimeout(()=>setToast(""),2600)}
  return <main className="shell">
    <aside>
      <div className="brand"><span className="brandmark">F</span><div><b>Fleetway</b><small>Operations portal</small></div></div>
      <nav>{nav.map(([n,i])=><button key={n} className={tab===n?"active":""} onClick={()=>setTab(n)}><Icon>{i}</Icon>{n}</button>)}</nav>
      <div className="aside-foot"><div className="help"><b>Need help?</b><span>View operations guide</span></div><div className="profile"><span className="avatar">{userName.slice(0,2).toUpperCase()}</span><div><b>{userName}</b><small>{view==="manager"?"Fleet manager":"Authorized viewer"}</small></div><button>•••</button></div></div>
    </aside>
    <section className="content">
      <header><button className="mobile">☰</button><div className="search">⌕ <input placeholder="Search fleet, people, routes..."/></div><div className="role-switch"><button className={view==="manager"?"selected":""} onClick={()=>setView("manager")}>Manager</button><button className={view==="viewer"?"selected":""} onClick={()=>setView("viewer")}>Viewer</button></div><button className="bell">♢<i/></button></header>
      <div className="page-head"><div><h1>{title}</h1><p>{subtitle}</p></div>{view==="manager"&&tab!=="Driver Activity"&&<button className="primary" onClick={()=>setModal(tab==="Schedule"?"schedule":tab==="Routes"?"route":tab==="Drivers & Assistants"?"person":tab==="Mileage & Fuel"?"fuelLog":tab==="Maintenance"?"maintenance":"vehicle")}>＋ {tab==="Overview"?"Register vehicle":tab==="Mileage & Fuel"?"Add mileage & petrol":tab==="Maintenance"?"Record maintenance":`Add ${tab.replace('Drivers & Assistants','person').replace('Schedule','trip')}`}</button>}</div>
      {view==="viewer"&&<div className="viewer-note"><Icon>✓</Icon><div><b>Authorized schedule view</b><span>You have read-only access to routes, assigned teams, and departure times.</span></div></div>}
      {loading?<div className="loading">Preparing today’s operations…</div>:tab==="Overview"?<Overview data={data} available={available} setTab={setTab}/>:<Records tab={tab} data={data}/>} 
    </section>
    {modal&&<Modal kind={modal} data={data} onClose={()=>setModal("")} onSaved={saved}/>} {toast&&<div className="toast">✓ {toast}</div>}
  </main>
}

function Overview({data,available,setTab}:{data:Data;available:number;setTab:(s:string)=>void}){
 const cards=[[data.vehicles.length,'Total vehicles',`${available} available`,'▣'],[data.people.filter(p=>p.role==='Driver').length,'Active drivers','2 on duty','♙'],[data.routes.length,'Active routes','All operating','⌁'],[data.schedules.length,"Today's trips",'1 currently on route','□']];
 return <><div className="stats">{cards.map((c,i)=><article key={String(c[1])}><div className={`stat-icon c${i}`}><Icon>{String(c[3])}</Icon></div><div><strong>{c[0]}</strong><span>{c[1]}</span><small><i/> {c[2]}</small></div></article>)}</div>
 <div className="grid"><section className="panel trips"><div className="panel-title"><div><h2>Today’s schedule</h2><p>Live vehicle movement and assignments</p></div><button onClick={()=>setTab('Schedule')}>View full schedule →</button></div><ScheduleTable rows={data.schedules}/></section>
 <section className="panel availability"><div className="panel-title"><div><h2>Fleet availability</h2><p>Current status across all vehicles</p></div></div><div className="donut" style={{'--p':`${Math.round((data.vehicles.filter(v=>v.status==='Available').length/data.vehicles.length)*100)}%`} as React.CSSProperties}><div><strong>{data.vehicles.filter(v=>v.status==='Available').length}</strong><span>available</span></div></div><div className="legend"><span><i className="green"/>Available <b>{data.vehicles.filter(v=>v.status==='Available').length}</b></span><span><i className="blue"/>On route <b>{data.vehicles.filter(v=>v.status==='On route').length}</b></span><span><i className="amber"/>Maintenance <b>{data.vehicles.filter(v=>v.status==='Maintenance').length}</b></span></div></section></div>
 <section className="panel people-strip"><div className="panel-title"><div><h2>Team availability</h2><p>Drivers and assistants ready for assignment</p></div><button onClick={()=>setTab('Drivers & Assistants')}>Manage team →</button></div><div className="person-cards">{data.people.slice(0,4).map(p=><div className="person" key={p.id}><span className="avatar alt">{String(p.name).split(' ').map(x=>x[0]).join('')}</span><div><b>{p.name}</b><span>{p.role}</span></div><em className={p.status==='Available'?'ok':''}>{p.status}</em></div>)}</div></section></>;
}

function Records({tab,data}:{tab:string;data:Data}){if(tab==='Schedule')return <section className="panel records"><ScheduleTable rows={data.schedules}/></section>;if(tab==='Mileage & Fuel')return <FuelRecords rows={data.mileageFuelLogs}/>;if(tab==='Maintenance')return <MaintenanceRecords rows={data.maintenanceLogs}/>;if(tab==='Driver Activity')return <DriverActivity trips={data.driverActivity} attendance={data.driverAttendance}/>; const rows=tab==='Vehicles'?data.vehicles:tab==='Routes'?data.routes:data.people; return <section className="panel records"><table><thead><tr>{(tab==='Vehicles'?['Vehicle','Type','Capacity','Latest mileage','Petrol used','Status']:tab==='Routes'?['Route','Journey','Estimated times','Goods & customer','Distance']:['Name & address','Role','Licence details','Phone','Status']).map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}>{tab==='Vehicles'?<><td><b>{r.plate}</b></td><td>{r.type}</td><td>{r.capacity} seats</td><td><b>{r.latest_odometer_km?Number(r.latest_odometer_km).toLocaleString()+' km':'Not recorded'}</b></td><td>{r.total_petrol_litres?`${r.total_petrol_litres} L`:'—'}</td><td><em className="pill">{r.status}</em></td></>:tab==='Routes'?<><td><b>{r.code}</b></td><td><b>{r.origin}</b><small>to {r.destination}</small></td><td><b>Depart {formatDateTime(r.estimated_departure)}</b><small>Arrive {formatDateTime(r.estimated_arrival)}</small></td><td><span className="cargo-summary">{r.cargo_summary||'No goods recorded'}</span></td><td>{r.distance} km</td></>:<><td><b>{r.name}</b><small>{r.address||'Address not recorded'}</small></td><td>{r.role}</td><td>{r.role==='Driver'?<><b>{r.license_class} · {r.driving_license}</b><small>Expires {r.license_expiry?new Date(String(r.license_expiry)).toLocaleDateString('en-SG',{day:'numeric',month:'short',year:'numeric'}):'—'}</small></>:'Not required'}</td><td>{r.phone}</td><td><em className="pill">{r.status}</em></td></>}</tr>)}</tbody></table></section>}
function tripStage(r:Row){return r.completed_at?'Completed':r.unloading_started_at?'Unloading':r.departed_at?'In transit':r.loading_started_at?'Loading':'Not started'}
function DriverActivity({trips,attendance}:{trips:Row[];attendance:Row[]}){const active=trips.filter(t=>!t.completed_at&&t.loading_started_at).length,present=attendance.filter(a=>!a.check_out_at&&a.work_date===new Date().toISOString().slice(0,10)).length;return <><div className="fuel-summary"><article><span>Drivers present today</span><strong>{present}</strong></article><article><span>Active routes</span><strong>{active}</strong></article><article><span>Completed reports</span><strong>{trips.filter(t=>t.completed_at).length}</strong></article></div><section className="panel records"><table><thead><tr><th>Driver & vehicle</th><th>Route</th><th>Stage</th><th>Mileage & photo</th><th>Fuel & photo</th><th>Last location</th></tr></thead><tbody>{trips.length?trips.map(r=><tr key={r.id}><td><b>{r.driver_name}</b><small>{r.plate}</small></td><td><b>{r.route_code}</b><small>{r.origin} → {r.destination}</small></td><td><em className="pill">{tripStage(r)}</em></td><td><b>{r.start_odometer_km?`${Number(r.start_odometer_km).toLocaleString()} km`:'—'}</b><small>{r.end_odometer_km?`End ${Number(r.end_odometer_km).toLocaleString()} km`:'Awaiting final reading'}</small>{r.mileage_photo_key&&<a className="evidence-link" href={`/api/driver/photos?key=${encodeURIComponent(String(r.mileage_photo_key))}`} target="_blank">View mileage photo</a>}</td><td><b>{r.fuel_litres?`${r.fuel_litres} L · $${Number(r.fuel_cost||0).toFixed(2)}`:'Awaiting report'}</b>{r.fuel_photo_key&&<a className="evidence-link" href={`/api/driver/photos?key=${encodeURIComponent(String(r.fuel_photo_key))}`} target="_blank">View fuel photo</a>}</td><td><b>{r.last_location_at?new Date(String(r.last_location_at)).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'No update'}</b><small>{r.last_latitude&&r.last_longitude?`${Number(r.last_latitude).toFixed(4)}, ${Number(r.last_longitude).toFixed(4)}`:'Location unavailable'}</small></td></tr>):<tr><td colSpan={6}>No driver route activity yet.</td></tr>}</tbody></table></section></>}
function FuelRecords({rows}:{rows:Row[]}){const litres=rows.reduce((sum,row)=>sum+Number(row.petrol_litres||0),0),cost=rows.reduce((sum,row)=>sum+Number(row.petrol_cost||0),0);return <><div className="fuel-summary"><article><span>Total petrol recorded</span><strong>{litres.toFixed(1)} L</strong></article><article><span>Total petrol cost</span><strong>${cost.toFixed(2)}</strong></article><article><span>Average price</span><strong>{litres?`$${(cost/litres).toFixed(2)} / L`:'—'}</strong></article></div><section className="panel records"><table><thead><tr><th>Date</th><th>Vehicle</th><th>Odometer</th><th>Petrol</th><th>Cost</th><th>Station & notes</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td><b>{new Date(String(r.recorded_at)).toLocaleDateString('en-SG',{day:'numeric',month:'short',year:'numeric'})}</b></td><td><b>{r.plate}</b><small>{r.vehicle_type}</small></td><td>{Number(r.odometer_km).toLocaleString()} km</td><td>{Number(r.petrol_litres).toFixed(1)} L</td><td>${Number(r.petrol_cost).toFixed(2)}</td><td><b>{r.station||'Not recorded'}</b><small>{r.notes||'—'}</small></td></tr>):<tr><td colSpan={6}>No mileage or petrol records yet.</td></tr>}</tbody></table></section></>}
function maintenanceStatus(row:Row){const today=new Date().toISOString().slice(0,10),current=Number(row.current_odometer_km||0),dueMileage=Number(row.next_due_odometer_km||0);if((row.next_due_date&&String(row.next_due_date)<today)||(dueMileage&&current>=dueMileage))return 'Overdue';const inThirty=new Date();inThirty.setDate(inThirty.getDate()+30);if((row.next_due_date&&String(row.next_due_date)<=inThirty.toISOString().slice(0,10))||(dueMileage&&current&&dueMileage-current<=1000))return 'Due soon';return 'Scheduled'}
function MaintenanceRecords({rows}:{rows:Row[]}){const overdue=rows.filter(r=>maintenanceStatus(r)==='Overdue').length,dueSoon=rows.filter(r=>maintenanceStatus(r)==='Due soon').length,cost=rows.reduce((s,r)=>s+Number(r.cost||0),0);return <><div className="fuel-summary"><article><span>Overdue maintenance</span><strong>{overdue}</strong></article><article><span>Due within 30 days / 1,000 km</span><strong>{dueSoon}</strong></article><article><span>Total maintenance cost</span><strong>${cost.toFixed(2)}</strong></article></div><section className="panel records"><table><thead><tr><th>Vehicle</th><th>Maintenance</th><th>Last completed</th><th>Next due</th><th>Workshop & cost</th><th>Status</th></tr></thead><tbody>{rows.length?rows.map(r=>{const status=maintenanceStatus(r);return <tr key={r.id}><td><b>{r.plate}</b><small>{r.vehicle_type}</small></td><td><b>{r.service_type}</b><small>{r.notes||'No notes'}</small></td><td><b>{new Date(String(r.completed_date)).toLocaleDateString('en-SG',{day:'numeric',month:'short',year:'numeric'})}</b><small>{r.completed_odometer_km?`${Number(r.completed_odometer_km).toLocaleString()} km`:'Mileage not recorded'}</small></td><td><b>{r.next_due_date?new Date(String(r.next_due_date)).toLocaleDateString('en-SG',{day:'numeric',month:'short',year:'numeric'}):'Date not set'}</b><small>{r.next_due_odometer_km?`${Number(r.next_due_odometer_km).toLocaleString()} km`:'Mileage not set'}</small></td><td><b>{r.workshop||'Not recorded'}</b><small>${Number(r.cost||0).toFixed(2)}</small></td><td><em className={`pill maintenance-${status.toLowerCase().replace(' ','-')}`}>{status}</em></td></tr>}):<tr><td colSpan={6}>No maintenance records yet.</td></tr>}</tbody></table></section></>}
function formatDateTime(value:string|number|null){return value?new Date(String(value)).toLocaleString('en-SG',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',hour12:false}):'Not set'}
function ScheduleTable({rows}:{rows:Row[]}){return <div className="table-wrap"><table><thead><tr><th>Departure</th><th>Route</th><th>Vehicle</th><th>Driver & assistant</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.time}</b><small>{new Date(String(r.date)).toLocaleDateString('en-SG',{day:'numeric',month:'short'})}</small></td><td><b>{r.route_code}</b><small>{r.origin} → {r.destination}</small></td><td>{r.plate}</td><td><b>{r.driver_name}</b><small>{r.assistant_name||'No assistant required'}</small></td><td><em className={`pill ${r.status==='On route'?'live':''}`}>{r.status}</em></td></tr>)}</tbody></table></div>}

function Modal({kind,data,onClose,onSaved}:{kind:string;data:Data;onClose:()=>void;onSaved:()=>void}){const [busy,setBusy]=useState(false);const [personRole,setPersonRole]=useState('Driver');const [cargo,setCargo]=useState([{goods:'',customer:''}]); async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const fd=new FormData(e.currentTarget);const body:{[key:string]:unknown}={...Object.fromEntries(fd),kind};if(kind==='route')body.goodsItems=cargo;const response=await fetch('/api/fleet',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(response.ok)onSaved();else setBusy(false)}
 const drivers=useMemo(()=>data.people.filter(p=>p.role==='Driver'),[data]);const assistants=useMemo(()=>data.people.filter(p=>p.role==='Assistant'),[data]);return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><form className="modal" onSubmit={submit}><div className="modal-head"><div><h2>{kind==='person'?'Register team member':kind==='schedule'?'Schedule a trip':kind==='fuelLog'?'Record mileage & petrol':kind==='maintenance'?'Record vehicle maintenance':`Add ${kind}`}</h2><p>Enter the required information below.</p></div><button type="button" onClick={onClose}>×</button></div>
 {kind==='vehicle'&&<><label>Registration number<input name="plate" required placeholder="e.g. SGK 4821"/></label><div className="fields"><label>Vehicle type<select name="type"><option>Coach</option><option>Mini bus</option><option>Van</option></select></label><label>Seat capacity<input name="capacity" required type="number" min="1" placeholder="44"/></label></div></>}
 {kind==='person'&&<><label>{personRole==='Driver'?'Driver name':'Assistant name'}<input name="name" required placeholder="Full legal name"/></label><div className="fields"><label>Role<select name="role" value={personRole} onChange={e=>setPersonRole(e.target.value)}><option>Driver</option><option>Assistant</option></select></label><label>Phone number<input name="phone" required type="tel" placeholder="9123 4567"/></label></div>{personRole==='Driver'&&<><div className="fields"><label>Licence class<select name="licenseClass" required><option value="">Select class</option><option>Class 2</option><option>Class 3</option><option>Class 3A</option><option>Class 4</option><option>Class 4A</option><option>Class 5</option></select></label><label>Driving licence<input name="drivingLicense" required placeholder="e.g. D-20481"/></label></div><label>Licence expiry date<input name="licenseExpiry" required type="date"/></label></>}<label>Address<textarea name="address" required={personRole==='Driver'} placeholder="Residential address" rows={3}/></label></>}
 {kind==='route'&&<><div className="fields"><label>Route code<input name="code" required placeholder="RT-401"/></label><label>Distance (km)<input name="distance" required type="number" min="1"/></label></div><label>Origin<input name="origin" required placeholder="Starting location"/></label><label>Destination<input name="destination" required placeholder="End location"/></label><div className="fields"><label>Estimated departure<input name="estimatedDeparture" required type="datetime-local"/></label><label>Estimated arrival<input name="estimatedArrival" required type="datetime-local"/></label></div><div className="subform"><div className="subform-head"><div><b>Goods carried</b><span>Record the cargo and its customer</span></div><button type="button" onClick={()=>setCargo([...cargo,{goods:'',customer:''}])}>＋ Add goods</button></div>{cargo.map((item,index)=><div className="cargo-row" key={index}><label>Goods<input required value={item.goods} onChange={e=>setCargo(cargo.map((x,i)=>i===index?{...x,goods:e.target.value}:x))} placeholder="e.g. Chilled food cartons"/></label><label>Customer<input required value={item.customer} onChange={e=>setCargo(cargo.map((x,i)=>i===index?{...x,customer:e.target.value}:x))} placeholder="Customer or company name"/></label>{cargo.length>1&&<button type="button" aria-label="Remove goods" onClick={()=>setCargo(cargo.filter((_,i)=>i!==index))}>×</button>}</div>)}</div></>}
 {kind==='schedule'&&<><label>Route<select name="routeId" required>{data.routes.map(x=><option value={String(x.id)} key={x.id}>{x.code} — {x.origin} to {x.destination}</option>)}</select></label><div className="fields"><label>Vehicle<select name="vehicleId">{data.vehicles.map(x=><option value={String(x.id)} key={x.id}>{x.plate}</option>)}</select></label><label>Driver<select name="driverId">{drivers.map(x=><option value={String(x.id)} key={x.id}>{x.name}</option>)}</select></label></div><label>Assistant<select name="assistantId"><option value="">Not required</option>{assistants.map(x=><option value={String(x.id)} key={x.id}>{x.name}</option>)}</select></label><div className="fields"><label>Date<input name="date" required type="date"/></label><label>Time<input name="time" required type="time"/></label></div></>}
 {kind==='fuelLog'&&<><label>Vehicle<select name="vehicleId" required><option value="">Select vehicle</option>{data.vehicles.map(x=><option value={String(x.id)} key={x.id}>{x.plate} — {x.type}</option>)}</select></label><div className="fields"><label>Date<input name="recordedAt" required type="date" defaultValue={new Date().toISOString().slice(0,10)}/></label><label>Odometer reading (km)<input name="odometerKm" required type="number" min="0" step="1" placeholder="e.g. 84520"/></label></div><div className="fields"><label>Petrol added (litres)<input name="petrolLitres" required type="number" min="0.01" step="0.01" placeholder="e.g. 42.5"/></label><label>Total petrol cost<input name="petrolCost" required type="number" min="0" step="0.01" placeholder="e.g. 118.40"/></label></div><label>Petrol station<input name="station" placeholder="Station name or location"/></label><label>Notes<textarea name="notes" rows={3} placeholder="Optional trip or receipt notes"/></label></>}
 {kind==='maintenance'&&<><label>Vehicle<select name="vehicleId" required><option value="">Select vehicle</option>{data.vehicles.map(x=><option value={String(x.id)} key={x.id}>{x.plate} — {x.type}</option>)}</select></label><label>Maintenance type<select name="serviceType" required><option value="">Select maintenance</option><option>Engine oil & filter change</option><option>Tyre inspection & rotation</option><option>Brake inspection</option><option>Battery check</option><option>Coolant service</option><option>Air filter replacement</option><option>Transmission service</option><option>General servicing</option><option>Other maintenance</option></select></label><div className="fields"><label>Completed date<input name="completedDate" required type="date" defaultValue={new Date().toISOString().slice(0,10)}/></label><label>Completed mileage (km)<input name="completedOdometerKm" type="number" min="0" step="1" placeholder="e.g. 84520"/></label></div><div className="subform"><div className="subform-head"><div><b>Next maintenance due</b><span>Enter a date, mileage, or both</span></div></div><div className="fields"><label>Next due date<input name="nextDueDate" type="date"/></label><label>Next due mileage (km)<input name="nextDueOdometerKm" type="number" min="1" step="1" placeholder="e.g. 94520"/></label></div></div><div className="fields"><label>Workshop / provider<input name="workshop" placeholder="Workshop name"/></label><label>Cost<input name="cost" type="number" min="0" step="0.01" defaultValue="0"/></label></div><label>Work performed / notes<textarea name="notes" rows={3} placeholder="Oil grade, tyre condition, parts replaced, recommendations..."/></label></>}
 <div className="actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':'Save record'}</button></div></form></div>}
